runtime: python39
entrypoint: gunicorn -b :$PORT backend.run:app

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  FLASK_ENV: "production"
  GOOGLE_CLOUD_PROJECT: "virtualtutor"

handlers:
- url: /static
  static_dir: frontend/dist/static
  secure: always

- url: /(.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot))$
  static_files: frontend/dist/\1
  upload: frontend/dist/.*\.(json|ico|js|css|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot)$
  secure: always

- url: /api/.*
  script: auto
  secure: always

- url: /.*
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html
  secure: always

includes:
- env_variables.yaml